//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WivaldyBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WivaldyBotResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WivaldyBotResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WivaldyBot.Properties.WivaldyBotResources", typeof(WivaldyBotResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last hour with yesterday same time.
        /// </summary>
        internal static string DialogCompareLastHourYesterdaySameTime {
            get {
                return ResourceManager.GetString("DialogCompareLastHourYesterdaySameTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today and yesterday.
        /// </summary>
        internal static string DialogCompareTodayYesterday {
            get {
                return ResourceManager.GetString("DialogCompareTodayYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday and day before.
        /// </summary>
        internal static string DialogCompareYesterdayDayBefore {
            get {
                return ResourceManager.GetString("DialogCompareYesterdayDayBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks, now I have your key and can get your electricity details! Just type &apos;electricity&apos;..
        /// </summary>
        internal static string DialogConfirmationKey {
            get {
                return ResourceManager.GetString("DialogConfirmationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string DialogConsumptionDay {
            get {
                return ResourceManager.GetString("DialogConsumptionDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last hour.
        /// </summary>
        internal static string DialogConsumptionHour {
            get {
                return ResourceManager.GetString("DialogConsumptionHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instant.
        /// </summary>
        internal static string DialogConsumptionInstant {
            get {
                return ResourceManager.GetString("DialogConsumptionInstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last day.
        /// </summary>
        internal static string DialogConsumptionLastDay {
            get {
                return ResourceManager.GetString("DialogConsumptionLastDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ups, something went wrong..
        /// </summary>
        internal static string DialogErrorMessage {
            get {
                return ResourceManager.GetString("DialogErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before get started, can you please give me your private key?.
        /// </summary>
        internal static string DialogGetPrivateKey {
            get {
                return ResourceManager.GetString("DialogGetPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your key has been removed.
        /// </summary>
        internal static string DialogKeyRemoved {
            get {
                return ResourceManager.GetString("DialogKeyRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to compare.
        /// </summary>
        internal static string DialogWelcomeCompare {
            get {
                return ResourceManager.GetString("DialogWelcomeCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to electricity.
        /// </summary>
        internal static string DialogWelcomeElectricity {
            get {
                return ResourceManager.GetString("DialogWelcomeElectricity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to key.
        /// </summary>
        internal static string DialogWelcomeKey {
            get {
                return ResourceManager.GetString("DialogWelcomeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logout.
        /// </summary>
        internal static string DialogWelcomeLogout {
            get {
                return ResourceManager.GetString("DialogWelcomeLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Wivaldy bot, just write anything and I&apos;ll help you :-)\r\Type &apos;key&apos; to get your current key, &apos;logout&apos; to clear your key..
        /// </summary>
        internal static string DialogWelcomeMessage {
            get {
                return ResourceManager.GetString("DialogWelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wivaldystring.
        /// </summary>
        internal static string WivaldiConnectionString {
            get {
                return ResourceManager.GetString("WivaldiConnectionString", resourceCulture);
            }
        }
    }
}
