//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WivaldyBot.Properties {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WivaldyBotResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WivaldyBotResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("WivaldyBot.Properties.WivaldyBotResources", typeof(WivaldyBotResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AlertAskInstant {
            get {
                return ResourceManager.GetString("AlertAskInstant", resourceCulture);
            }
        }
        
        internal static string AlertChange {
            get {
                return ResourceManager.GetString("AlertChange", resourceCulture);
            }
        }
        
        internal static string AlertChangeInstant {
            get {
                return ResourceManager.GetString("AlertChangeInstant", resourceCulture);
            }
        }
        
        internal static string AlertChangeTotal {
            get {
                return ResourceManager.GetString("AlertChangeTotal", resourceCulture);
            }
        }
        
        internal static string AlertInstant {
            get {
                return ResourceManager.GetString("AlertInstant", resourceCulture);
            }
        }
        
        internal static string AlertInterval {
            get {
                return ResourceManager.GetString("AlertInterval", resourceCulture);
            }
        }
        
        internal static string AlertReallySorry {
            get {
                return ResourceManager.GetString("AlertReallySorry", resourceCulture);
            }
        }
        
        internal static string AlertRetryInterval {
            get {
                return ResourceManager.GetString("AlertRetryInterval", resourceCulture);
            }
        }
        
        internal static string AlertRetryThreshold {
            get {
                return ResourceManager.GetString("AlertRetryThreshold", resourceCulture);
            }
        }
        
        internal static string AlertThresholdkWh {
            get {
                return ResourceManager.GetString("AlertThresholdkWh", resourceCulture);
            }
        }
        
        internal static string AlertThresholdWatts {
            get {
                return ResourceManager.GetString("AlertThresholdWatts", resourceCulture);
            }
        }
        
        internal static string AlertTotal {
            get {
                return ResourceManager.GetString("AlertTotal", resourceCulture);
            }
        }
        
        internal static string CompareConsumptionBad {
            get {
                return ResourceManager.GetString("CompareConsumptionBad", resourceCulture);
            }
        }
        
        internal static string CompareConsumptionGood {
            get {
                return ResourceManager.GetString("CompareConsumptionGood", resourceCulture);
            }
        }
        
        internal static string CompareConsumptionkWh {
            get {
                return ResourceManager.GetString("CompareConsumptionkWh", resourceCulture);
            }
        }
        
        internal static string CompareConsumptionLastHourYesterday {
            get {
                return ResourceManager.GetString("CompareConsumptionLastHourYesterday", resourceCulture);
            }
        }
        
        internal static string CompareConsumptionTodayYesterday {
            get {
                return ResourceManager.GetString("CompareConsumptionTodayYesterday", resourceCulture);
            }
        }
        
        internal static string CompareConsumptionYesterdayDayBefore {
            get {
                return ResourceManager.GetString("CompareConsumptionYesterdayDayBefore", resourceCulture);
            }
        }
        
        internal static string DialogActivitySelect {
            get {
                return ResourceManager.GetString("DialogActivitySelect", resourceCulture);
            }
        }
        
        internal static string DialogActivityTellUs {
            get {
                return ResourceManager.GetString("DialogActivityTellUs", resourceCulture);
            }
        }
        
        internal static string DialogCompareLastHourYesterdaySameTime {
            get {
                return ResourceManager.GetString("DialogCompareLastHourYesterdaySameTime", resourceCulture);
            }
        }
        
        internal static string DialogCompareTodayYesterday {
            get {
                return ResourceManager.GetString("DialogCompareTodayYesterday", resourceCulture);
            }
        }
        
        internal static string DialogCompareYesterdayDayBefore {
            get {
                return ResourceManager.GetString("DialogCompareYesterdayDayBefore", resourceCulture);
            }
        }
        
        internal static string DialogConfirmationKey {
            get {
                return ResourceManager.GetString("DialogConfirmationKey", resourceCulture);
            }
        }
        
        internal static string DialogConsumptionDay {
            get {
                return ResourceManager.GetString("DialogConsumptionDay", resourceCulture);
            }
        }
        
        internal static string DialogConsumptionHour {
            get {
                return ResourceManager.GetString("DialogConsumptionHour", resourceCulture);
            }
        }
        
        internal static string DialogConsumptionInstant {
            get {
                return ResourceManager.GetString("DialogConsumptionInstant", resourceCulture);
            }
        }
        
        internal static string DialogConsumptionLastDay {
            get {
                return ResourceManager.GetString("DialogConsumptionLastDay", resourceCulture);
            }
        }
        
        internal static string DialogElectricityConsumption {
            get {
                return ResourceManager.GetString("DialogElectricityConsumption", resourceCulture);
            }
        }
        
        internal static string DialogElectricityTellUs {
            get {
                return ResourceManager.GetString("DialogElectricityTellUs", resourceCulture);
            }
        }
        
        internal static string DialogErrorMessage {
            get {
                return ResourceManager.GetString("DialogErrorMessage", resourceCulture);
            }
        }
        
        internal static string DialogGetPrivateKey {
            get {
                return ResourceManager.GetString("DialogGetPrivateKey", resourceCulture);
            }
        }
        
        internal static string DialogKeyIs {
            get {
                return ResourceManager.GetString("DialogKeyIs", resourceCulture);
            }
        }
        
        internal static string DialogKeyRemoved {
            get {
                return ResourceManager.GetString("DialogKeyRemoved", resourceCulture);
            }
        }
        
        internal static string DialogNo {
            get {
                return ResourceManager.GetString("DialogNo", resourceCulture);
            }
        }
        
        internal static string DialogWelcomeAlert {
            get {
                return ResourceManager.GetString("DialogWelcomeAlert", resourceCulture);
            }
        }
        
        internal static string DialogWelcomeCompare {
            get {
                return ResourceManager.GetString("DialogWelcomeCompare", resourceCulture);
            }
        }
        
        internal static string DialogWelcomeElectricity {
            get {
                return ResourceManager.GetString("DialogWelcomeElectricity", resourceCulture);
            }
        }
        
        internal static string DialogWelcomeKey {
            get {
                return ResourceManager.GetString("DialogWelcomeKey", resourceCulture);
            }
        }
        
        internal static string DialogWelcomeLogout {
            get {
                return ResourceManager.GetString("DialogWelcomeLogout", resourceCulture);
            }
        }
        
        internal static string DialogWelcomeMessage {
            get {
                return ResourceManager.GetString("DialogWelcomeMessage", resourceCulture);
            }
        }
        
        internal static string DialogYes {
            get {
                return ResourceManager.GetString("DialogYes", resourceCulture);
            }
        }
        
        internal static string TotalConsumptionInstant {
            get {
                return ResourceManager.GetString("TotalConsumptionInstant", resourceCulture);
            }
        }
        
        internal static string TotalConsumptionKwh {
            get {
                return ResourceManager.GetString("TotalConsumptionKwh", resourceCulture);
            }
        }
        
        internal static string TotalConsumptionLastHour {
            get {
                return ResourceManager.GetString("TotalConsumptionLastHour", resourceCulture);
            }
        }
        
        internal static string TotalConsumptionNoData {
            get {
                return ResourceManager.GetString("TotalConsumptionNoData", resourceCulture);
            }
        }
        
        internal static string TotalConsumptionNow {
            get {
                return ResourceManager.GetString("TotalConsumptionNow", resourceCulture);
            }
        }
        
        internal static string TotalConsumptionTodayIs {
            get {
                return ResourceManager.GetString("TotalConsumptionTodayIs", resourceCulture);
            }
        }
        
        internal static string TotalConsumptionYesterday {
            get {
                return ResourceManager.GetString("TotalConsumptionYesterday", resourceCulture);
            }
        }
        
        internal static string WivaldiConnectionString {
            get {
                return ResourceManager.GetString("WivaldiConnectionString", resourceCulture);
            }
        }
        
        internal static string AlertEnd {
            get {
                return ResourceManager.GetString("AlertEnd", resourceCulture);
            }
        }
        
        internal static string AlertEndMax {
            get {
                return ResourceManager.GetString("AlertEndMax", resourceCulture);
            }
        }
        
        internal static string AlertExceedInstant {
            get {
                return ResourceManager.GetString("AlertExceedInstant", resourceCulture);
            }
        }
        
        internal static string AlertExceedTotal {
            get {
                return ResourceManager.GetString("AlertExceedTotal", resourceCulture);
            }
        }
        
        internal static string AlertMaxTime {
            get {
                return ResourceManager.GetString("AlertMaxTime", resourceCulture);
            }
        }
        
        internal static string AlertMinSec {
            get {
                return ResourceManager.GetString("AlertMinSec", resourceCulture);
            }
        }
        
        internal static string AlertOK {
            get {
                return ResourceManager.GetString("AlertOK", resourceCulture);
            }
        }
        
        internal static string AlertRetryMaxTime {
            get {
                return ResourceManager.GetString("AlertRetryMaxTime", resourceCulture);
            }
        }
        
        internal static string AlertTime {
            get {
                return ResourceManager.GetString("AlertTime", resourceCulture);
            }
        }
        
        internal static string AlertChangeSwitch {
            get {
                return ResourceManager.GetString("AlertChangeSwitch", resourceCulture);
            }
        }
        
        internal static string AlertExceedSwitch {
            get {
                return ResourceManager.GetString("AlertExceedSwitch", resourceCulture);
            }
        }
        
        internal static string AlertSwitch {
            get {
                return ResourceManager.GetString("AlertSwitch", resourceCulture);
            }
        }
        
        internal static string AlertThresholdSwitch {
            get {
                return ResourceManager.GetString("AlertThresholdSwitch", resourceCulture);
            }
        }
    }
}
