//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WivaldyBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WivaldyBotResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WivaldyBotResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WivaldyBot.Properties.WivaldyBotResources", typeof(WivaldyBotResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which consumption alert do you want?.
        /// </summary>
        internal static string AlertAskInstant {
            get {
                return ResourceManager.GetString("AlertAskInstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your existing alert?.
        /// </summary>
        internal static string AlertChange {
            get {
                return ResourceManager.GetString("AlertChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every {0} seconds with {1} watts threshold..
        /// </summary>
        internal static string AlertChangeInstant {
            get {
                return ResourceManager.GetString("AlertChangeInstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check remote command every {0} seconds.
        /// </summary>
        internal static string AlertChangeSwitch {
            get {
                return ResourceManager.GetString("AlertChangeSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every {0} seconds with {1} kWh threshold..
        /// </summary>
        internal static string AlertChangeTotal {
            get {
                return ResourceManager.GetString("AlertChangeTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *End of Alerts.* Don&apos;t hsitate to resetup alerts if you want..
        /// </summary>
        internal static string AlertEnd {
            get {
                return ResourceManager.GetString("AlertEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *End of Alerts.* You&apos;ve reach the maximum number of alerts for this session. Please schedule another alert to receive more alerts..
        /// </summary>
        internal static string AlertEndMax {
            get {
                return ResourceManager.GetString("AlertEndMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Your consumption exceed your threshold** and it is {0} watts vs {1} watts.
        /// </summary>
        internal static string AlertExceedInstant {
            get {
                return ResourceManager.GetString("AlertExceedInstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Alert on switch** {0}.
        /// </summary>
        internal static string AlertExceedSwitch {
            get {
                return ResourceManager.GetString("AlertExceedSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Your consumption exceed your threshold** and it is {0} kWh vs {1} kWh.
        /// </summary>
        internal static string AlertExceedTotal {
            get {
                return ResourceManager.GetString("AlertExceedTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instant.
        /// </summary>
        internal static string AlertInstant {
            get {
                return ResourceManager.GetString("AlertInstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pelase enter the inteval in seconds.
        /// </summary>
        internal static string AlertInterval {
            get {
                return ResourceManager.GetString("AlertInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of minutes you can get notifications is {0} minutes, so setting it to the maximum..
        /// </summary>
        internal static string AlertMaxTime {
            get {
                return ResourceManager.GetString("AlertMaxTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum number of seconds between two refresh is fiwed at {0}, so setting it to the minimum..
        /// </summary>
        internal static string AlertMinSec {
            get {
                return ResourceManager.GetString("AlertMinSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have setup a new alert: .
        /// </summary>
        internal static string AlertOK {
            get {
                return ResourceManager.GetString("AlertOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m really sorry, I didn&apos;t understand, please try again later..
        /// </summary>
        internal static string AlertReallySorry {
            get {
                return ResourceManager.GetString("AlertReallySorry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m sorry I did not undersant, plrease try again to enter a number of seconds.
        /// </summary>
        internal static string AlertRetryInterval {
            get {
                return ResourceManager.GetString("AlertRetryInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m sorry I did not undersant, plrease try again to enter a number of minutes..
        /// </summary>
        internal static string AlertRetryMaxTime {
            get {
                return ResourceManager.GetString("AlertRetryMaxTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m sorry I did not undersant, plrease try again to enter a number for the threshold.Make sure you are using {0} as a decimal separator..
        /// </summary>
        internal static string AlertRetryThreshold {
            get {
                return ResourceManager.GetString("AlertRetryThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch.
        /// </summary>
        internal static string AlertSwitch {
            get {
                return ResourceManager.GetString("AlertSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your threshold in kWh.
        /// </summary>
        internal static string AlertThresholdkWh {
            get {
                return ResourceManager.GetString("AlertThresholdkWh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter SWITCH TODO NOTIMPLEMENTED.
        /// </summary>
        internal static string AlertThresholdSwitch {
            get {
                return ResourceManager.GetString("AlertThresholdSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your threshold in watts.
        /// </summary>
        internal static string AlertThresholdWatts {
            get {
                return ResourceManager.GetString("AlertThresholdWatts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the maximum minutes you want to receive notifications..
        /// </summary>
        internal static string AlertTime {
            get {
                return ResourceManager.GetString("AlertTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string AlertTotal {
            get {
                return ResourceManager.GetString("AlertTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ![Bad]({0}/Images/wivaldy_icon_home-sleepy-200x200.png).
        /// </summary>
        internal static string CompareConsumptionBad {
            get {
                return ResourceManager.GetString("CompareConsumptionBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ![Good]({0}/Images/wivaldy_icon_home-overload-200x200.png).
        /// </summary>
        internal static string CompareConsumptionGood {
            get {
                return ResourceManager.GetString("CompareConsumptionGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} kWh vs {1} kWh.\r\n\r\n.
        /// </summary>
        internal static string CompareConsumptionkWh {
            get {
                return ResourceManager.GetString("CompareConsumptionkWh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your total consumption compare today last hour and yesterday same time is: .
        /// </summary>
        internal static string CompareConsumptionLastHourYesterday {
            get {
                return ResourceManager.GetString("CompareConsumptionLastHourYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your total consumption compare from yesterday and today at the same time is: .
        /// </summary>
        internal static string CompareConsumptionTodayYesterday {
            get {
                return ResourceManager.GetString("CompareConsumptionTodayYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your total consumption compare from yesterday and the day before is: .
        /// </summary>
        internal static string CompareConsumptionYesterdayDayBefore {
            get {
                return ResourceManager.GetString("CompareConsumptionYesterdayDayBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your activity.
        /// </summary>
        internal static string DialogActivitySelect {
            get {
                return ResourceManager.GetString("DialogActivitySelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell us what you want to do.
        /// </summary>
        internal static string DialogActivityTellUs {
            get {
                return ResourceManager.GetString("DialogActivityTellUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last hour with yesterday same time.
        /// </summary>
        internal static string DialogCompareLastHourYesterdaySameTime {
            get {
                return ResourceManager.GetString("DialogCompareLastHourYesterdaySameTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today and yesterday.
        /// </summary>
        internal static string DialogCompareTodayYesterday {
            get {
                return ResourceManager.GetString("DialogCompareTodayYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday and day before.
        /// </summary>
        internal static string DialogCompareYesterdayDayBefore {
            get {
                return ResourceManager.GetString("DialogCompareYesterdayDayBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks, now I have your key and can get your electricity details! Just type &apos;electricity&apos;..
        /// </summary>
        internal static string DialogConfirmationKey {
            get {
                return ResourceManager.GetString("DialogConfirmationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string DialogConsumptionDay {
            get {
                return ResourceManager.GetString("DialogConsumptionDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last hour.
        /// </summary>
        internal static string DialogConsumptionHour {
            get {
                return ResourceManager.GetString("DialogConsumptionHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instant.
        /// </summary>
        internal static string DialogConsumptionInstant {
            get {
                return ResourceManager.GetString("DialogConsumptionInstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last day.
        /// </summary>
        internal static string DialogConsumptionLastDay {
            get {
                return ResourceManager.GetString("DialogConsumptionLastDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electric consumption.
        /// </summary>
        internal static string DialogElectricityConsumption {
            get {
                return ResourceManager.GetString("DialogElectricityConsumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the cunsomption you want to see.
        /// </summary>
        internal static string DialogElectricityTellUs {
            get {
                return ResourceManager.GetString("DialogElectricityTellUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ups, something went wrong..
        /// </summary>
        internal static string DialogErrorMessage {
            get {
                return ResourceManager.GetString("DialogErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before get started, can you please give me your private key?.
        /// </summary>
        internal static string DialogGetPrivateKey {
            get {
                return ResourceManager.GetString("DialogGetPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your key is {0}.
        /// </summary>
        internal static string DialogKeyIs {
            get {
                return ResourceManager.GetString("DialogKeyIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your key has been removed.
        /// </summary>
        internal static string DialogKeyRemoved {
            get {
                return ResourceManager.GetString("DialogKeyRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string DialogNo {
            get {
                return ResourceManager.GetString("DialogNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alert.
        /// </summary>
        internal static string DialogWelcomeAlert {
            get {
                return ResourceManager.GetString("DialogWelcomeAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to compare.
        /// </summary>
        internal static string DialogWelcomeCompare {
            get {
                return ResourceManager.GetString("DialogWelcomeCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to electricity.
        /// </summary>
        internal static string DialogWelcomeElectricity {
            get {
                return ResourceManager.GetString("DialogWelcomeElectricity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to key.
        /// </summary>
        internal static string DialogWelcomeKey {
            get {
                return ResourceManager.GetString("DialogWelcomeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logout.
        /// </summary>
        internal static string DialogWelcomeLogout {
            get {
                return ResourceManager.GetString("DialogWelcomeLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Wivaldy bot, just write anything and I&apos;ll help you :-) Type &apos;key&apos; to get your current key, &apos;logout&apos; to clear your key..
        /// </summary>
        internal static string DialogWelcomeMessage {
            get {
                return ResourceManager.GetString("DialogWelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string DialogYes {
            get {
                return ResourceManager.GetString("DialogYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} watts..
        /// </summary>
        internal static string TotalConsumptionInstant {
            get {
                return ResourceManager.GetString("TotalConsumptionInstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} kWh. . Cost is approximately {1} €..
        /// </summary>
        internal static string TotalConsumptionKwh {
            get {
                return ResourceManager.GetString("TotalConsumptionKwh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your total consumption for last hour is: .
        /// </summary>
        internal static string TotalConsumptionLastHour {
            get {
                return ResourceManager.GetString("TotalConsumptionLastHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there is no data available..
        /// </summary>
        internal static string TotalConsumptionNoData {
            get {
                return ResourceManager.GetString("TotalConsumptionNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your instant consumption is: .
        /// </summary>
        internal static string TotalConsumptionNow {
            get {
                return ResourceManager.GetString("TotalConsumptionNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your total consumption for today is: .
        /// </summary>
        internal static string TotalConsumptionTodayIs {
            get {
                return ResourceManager.GetString("TotalConsumptionTodayIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your total consumption for yesterday is: .
        /// </summary>
        internal static string TotalConsumptionYesterday {
            get {
                return ResourceManager.GetString("TotalConsumptionYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wivaldystring.
        /// </summary>
        internal static string WivaldiConnectionString {
            get {
                return ResourceManager.GetString("WivaldiConnectionString", resourceCulture);
            }
        }
    }
}
